---

  - name: Rebooting Server
    command: /sbin/shutdown -r now
    tags: reboot

  - name: Waiting for port after reboot
    wait_for: host={{ inventory_hostname }} port={{ reboot_check_port | default('22') }} delay={{ wait_delay | default('60') }} state=started
    connection: local
    sudo: false
    tags: reboot

  - name: pausing
    pause: minutes={{ pause_between_host_restarts | default('1') }}
    tags: reboot
