---

  - name: Rebooting Server
    command: sleep 2 && /sbin/shutdown -r now &
    tags: reboot
  
  - name: Waiting for port to go down from server reboot
    wait_for: host={{ inventory_hostna,e }} port={{ reboot_check_port | default('22') }} timeout={{ wait_timeout | default('600') }} state=stopped

  - name: Waiting for port to come back after reboot
    wait_for: host={{ inventory_hostname }} port={{ reboot_check_port | default('22') }} delay={{ wait_delay | default('120') }} timeout={{ wait_timeout | default('600') }} state=started
    connection: local
    sudo: false
    tags: reboot

  - name: pausing
    pause: minutes={{ pause_between_host_restarts | default('1') }}
    tags: reboot
