#!/usr/bin/env ansible-playbook -f 50
---
#This playbook requires the following variables:
# hosts - this is the host(s) that you are trying to run on any host in the hosts file is valid

#Usage: 
#Updating a package: ansible-playbook patching.yaml -k -K --extra-vars "hosts=dev-all"

- hosts: '{{ hosts }}'
  sudo: yes
  tasks:
  - include: /etc/ansible/tasks/remove-old-kernels.yaml
  - include: /etc/ansible/tasks/patching.yaml
